name: main
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Run Prisma Cloud
            id: prismacloud
            uses: bridgecrewio/checkov-action@master 
            env:
              PRISMA_API_URL: https://api2.prismacloud.io
            with:
              api-key: ${{ secrets.BC_API_KEY }}
              enable_secrets_scan_all_files: true
